pb33f/libopenapi-validator

- go.mod
- go.sum
- parameters/cookie_parameters.go
- parameters/header_parameters.go
- parameters/header_parameters_test.go
- parameters/path_parameters.go
- parameters/path_parameters_test.go
- parameters/query_parameters.go
- parameters/validation_functions.go
- paths/paths.go
- paths/paths_test.go
- requests/validate_body_test.go
- responses/validate_body_test.go
- schema_validation/locate_schema_property.go
- schema_validation/locate_schema_property_test.go
- schema_validation/validate_document.go
- schema_validation/validate_document_test.go
- schema_validation/validate_schema.go
- validator_examples_test.go
- validator_test.go
Some issues with handling schemas when used as a library.
> A number of fixes after implementing in vacuum

- responses/validate_body.go
- responses/validate_body_test.go
Empty content in response definitions is now allowed. 
```
openapi: "3.0.0"
info:
title: Healthcheck
version: '0.1.0'
paths:
/health:
get:
responses:
'200':
description: pet response
content: {}
```
Is, now acceptable.
Fixes #14
> Allow empty content type to pass validation.

- requests/validate_request.go
- responses/validate_response.go
- schema_validation/validate_schema.go
As reported in #16, types may not always exist (so the schema is completely invalid anyway). However, it’s essential to make sure that we check for the type before using it.
> Always check a schema has a `type` when returning errors.

- parameters/query_parameters.go
A panic was being thrown when a schema is missing a type and checking for a query param. All schemas should always have a type, assumption however is the mother of all f**kups.
> Fixed panic when type on schema is empty. #22

- schema_validation/validate_schema.go
- schema_validation/validate_schema_test.go
vacuum OWASP rules depend on the validator being set in 2020 mode, vs Draft4. If we use the version to set the draft when validating inline schemas, we end up blowing up half of vacuum.
vacuum is a priority.
> Had to rollback some changes. v0.0.22

- requests/validate_body.go
- requests/validate_body_test.go
Use the early-out pattern to reduce code complexity.
None of the existing logic should have changed, and all tests pass.
@daveshanley Can you fact check me at line 40? At this point, are there any errors that could occur here?
> refactor(ValidateRequestBody): reduce cyclomatic complexity and indent

- errors/parameter_errors.go
- parameters/cookie_parameters.go
- parameters/header_parameters.go
- parameters/path_parameters.go
- parameters/query_parameters.go
- parameters/validation_functions.go
Borked tests, because enums were broken, and now they are fixed.
> Fixed broken tests after libopenapi upgrade

- responses/validate_body.go
- responses/validate_body_test.go
Regression introduced with a safety check, regression has been undone.
> Addressed issue #48

- parameters/query_parameters.go
- parameters/query_parameters_test.go
- parameters/validate_parameter.go
add the support to validate query simple params like
```yaml
parameters:
- name: fishy
in: query
required: true
schema:
type: string
minLength: 4
```
```yaml
parameters:
- name: fishy
in: query
required: true
schema:
type: number
minimum: 200
```
> query param validation

- parameters/path_parameters.go
- parameters/path_parameters_test.go
- paths/paths.go
- paths/paths_test.go
- validator_examples_test.go
- validator_test.go
this PR depends on https://github.com/pb33f/libopenapi-validator/pull/55 for the validateSimpleParam function
it should fix https://github.com/pb33f/libopenapi-validator/issues/43
> String and number path param validation

- paths/paths.go
- paths/paths_test.go
Hi there. Thank you for GREAT pkgs!
I fixed a problem where checkPathAgainstBase was unintentionally changing the basePath.
Also added a test that was panicky before the fix.
```console
$ go test ./paths/... -run TestNewValidator_FindPathMissingWithBaseURLInServer
--- FAIL: TestNewValidator_FindPathMissingWithBaseURLInServer (0.00s)
panic: runtime error: index out of range [-1] [recovered]
panic: runtime error: index out of range [-1]
goroutine 19 [running]:
testing.tRunner.func1.2({0x100ff8840, 0x140000181e0})
/Users/k1low/sdk/go1.22.1/src/testing/testing.go:1631 +0x1c4
testing.tRunner.func1()
/Users/k1low/sdk/go1.22.1/src/testing/testing.go:1634 +0x33c
panic({0x100ff8840?, 0x140000181e0?})
/Users/k1low/sdk/go1.22.1/src/runtime/panic.go:770 +0x124 …
```
> Fixed checkPathAgainstBase modifying basePaths unintentionally.

- parameters/validate_security.go
- parameters/validate_security_test.go
Hi there.
I fixed a problem when the securityScheme to be referenced does not exist.
```
--- FAIL: TestParamValidator_ValidateSecurity_MissingSecuritySchemes (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10242c5d8]
goroutine 733 [running]:
testing.tRunner.func1.2({0x1025a04a0, 0x1029ea420})
/Users/k1low/sdk/go1.22.1/src/testing/testing.go:1631 +0x1c4
testing.tRunner.func1()
/Users/k1low/sdk/go1.22.1/src/testing/testing.go:1634 +0x33c
panic({0x1025a04a0?, 0x1029ea420?})
/Users/k1low/sdk/go1.22.1/src/runtime/panic.go:770 +0x124
github.com/pb33f/libopenapi-validator/parameters.(*paramValidator).ValidateSecurity(0x1 …
```
> Raise an error if the securityScheme to be referenced does not exist.

- errors/error_utilities.go
- errors/request_errors.go
- errors/validation_error.go
- parameters/cookie_parameters.go
- parameters/cookie_parameters_test.go
- parameters/header_parameters.go
- parameters/header_parameters_test.go
- parameters/path_parameters.go
- parameters/path_parameters_test.go
- parameters/query_parameters.go
- parameters/query_parameters_test.go
- parameters/validate_security.go
- parameters/validate_security_test.go
- paths/paths.go
- requests/validate_body.go
- requests/validate_body_test.go
- responses/validate_body.go
- responses/validate_body_test.go
I added some request information to the validation error struct. 
Rather than modifying this in constructors, I figured it would be a lot easier to populate this as the last step during validation. If that's not the right approach, I can convert it to a constructor oriented method.
> Added request information to all non-schema validation errors

- responses/validate_body.go
- responses/validate_body_test.go
- validator_test.go
Hi all.
This fix supports the range definition for response codes.
ref: https://swagger.io/docs/specification/describing-responses/
> Support range definition for response codes.

- schema_validation/locate_schema_property.go
A race condition in vacuum is thrown during tests, this slight change fixes that by swapping over to a channel vs a timeout.
> Fixed issue with race conditions in test further up the stack.

- responses/response_body.go
- responses/validate_body.go
Hi @daveshanley .
responseBodyValidator now also uses sync.Map 👍 
ref: https://github.com/k1LoW/runn/issues/889
> Use sync.Map like requestBodyValidator

- requests/validate_request.go
- requests/validate_request_test.go
This pull request introduces improved error handling for the JSON schema compilation process in the request validation logic. Previously, the code did not handle potential errors from the compiler, which caused the code to panic when attempting to validate the request body.
The change will improve reliability by ensuring that schema compilation errors are gracefully handled, thus improving the stability of the request body schema validation process.
Additionally, this will facilitate quicker debugging and resolution of issues related to invalid schemas.
> Check and handle compiler err on compile req body

- requests/validate_body.go
- requests/validate_body_test.go
fixes https://github.com/pb33f/libopenapi-validator/issues/70
> request body is not required by default

- go.mod
- go.sum
- requests/validate_body_test.go
- requests/validate_request.go
If a schema has no type, it would cause a panic. This has now been resolved.
> Addressed issue #75

- requests/validate_body.go
- validator.go
- validator_examples_test.go
- validator_test.go
Implements the feature requested in: https://github.com/pb33f/libopenapi-validator/issues/79
> fix: add ValidateHttpRequestSync method for synschronous request validation

- responses/validate_body.go
- responses/validate_body_test.go
Fix panics caused by ResponseContentTypeNotFound in the case of a response with a range status code.
> Support response content-type not found with range status code.

- errors/validation_error.go
- paths/paths.go
- paths/paths_test.go
The idea is to have a more precise error reporting from the FindPath function, before it could yield a path not found validation error, with this proposed change we will have a path not found or operation not found error.
this may be a breaking change for some implementation that were reliant on IsPathMissingError to filter any error regarding a find path validation error
> FindPath reports path and operation not found

- parameters/validate_security.go
- parameters/validate_security_test.go
Match OAPI spec by validating security if 1 of any of the schemes is true, including an empty scheme.  Fixes https://github.com/pb33f/libopenapi-validator/issues/97
> Add support for multiple possible security schemes without requiring they're all true

- paths/paths.go
- paths/paths_test.go
Escaped parts of the url should not be a part of the stripped URL
> Use escaped path for StripRequestPath

- responses/validate_body_test.go
- responses/validate_response.go
- Check that the response body is empty by using the [http.NoBody] variable as the http.Client and http.Transport always guarantees that the body will never be nil hence the condition `response.Body == nil` is irrelevant in real word scenarios. 
- Adjust test accordingly
source : 
https://cs.opensource.google/go/go/+/refs/tags/go1.24.1:src/net/http/response.go
```
// Body represents the response body.
//
// The response body is streamed on demand as the Body field
// is read. If the network connection fails or the server
// terminates the response, Body.Read calls return an error.
//
// The http Client and Transport guarantee that Body is always
// non-nil, even on responses without a body or responses with
// a zero-length body. It is the caller's responsibility to
// close Body. The …
```
> fix: check for empty body in response using http.NoBody

- go.mod
- validator.go
- validator_test.go
Currently, when initializing validator.NewValidator with a custom regex engine, that engine is not passed down to the `ValidateDocument()` function.
For example:
```
validator, errs := validator.NewValidator(doc, config.WithRegexEngine(customRegexEngine))
if len(errs) > 0 {
log.Fatal(errs)
return 
}
docValid, valErrors := validator.ValidateDocument()
if len(valErrors) > 0 {
log.Fatal(valErrors)
return
}
```
In this case, although config.WithRegexEngine(customRegexEngine) is provided during initialization, it is not used during validation, because ValidateDocument() does not forward the option.
This PR resolves the issue by ensuring v.options.RegexEngine is passed into ValidateOpenAPIDocument using the config.WithRegexEngine option. This ensures that any custom regex engine specified …
> fix: pass validator config options when validating OpenAPI doc

- parameters/query_parameters.go
- parameters/query_parameters_test.go
fix [#135](https://github.com/pb33f/libopenapi-validator/issues/135)
> fix:the validation error is overwritten when one of the multiple fields contains an invalid parameter.

- README.md
- cmd/validate/main.go
This PR introduces a cmd tool for quickly validating OpenAPI documents via the CLI.
It supports a --regexengine flag, allowing users to specify custom regex parsing options. This enables validation of OpenAPI documents using different regex engines and flags depending on their needs.
> feat: cli cmd to validate oas spec

- parameters/query_parameters_test.go
- parameters/validation_functions.go
Resolves #146.
Check the item against the enum definition when validating arrays of query parameters. Previously, the unparsed query parameter value was used. This was problematic for non-exploded-form-style-arrays. In that case, validation errors would be thrown for correct requests. For example, if you accept only `cod` and `haddock`, and the parameter is set to `cod,haddock`, it'd test `cod,haddock` instead of `cod` and `haddock`.
> Check items when validating enums in array query parameters.

- helpers/path_finder.go
- helpers/path_finder_test.go
Two new helper functions for https://github.com/pb33f/libopenapi-validator/issues/120
in the `helpers` module.
`ExtractJSONPathFromValidationError(e *jsonschema.ValidationError) string`
and
`ExtractJSONPathsFromValidationErrors(errors []*jsonschema.ValidationError) []string`
> Added a new helper function for #120

- helpers/ignore_regex.go
- schema_validation/validate_schema_test.go
it’s less strict now, and fixes a known issue.
https://github.com/daveshanley/vacuum/issues/520
> Upgraded ignore regex
